export const toDelete = [
    {           name: 'Tickets',          endpoint: '/Assistance/Ticket' },
    {           name: 'Changes',          endpoint: '/Assistance/Change' },
    {           name: 'Problems',         endpoint: '/Assistance/Problem' },
    {           name: 'Computers',        endpoint: '/Assets/Computer' },
    {           name: 'Monitors',         endpoint: '/Assets/Monitor' },
    {           name: 'NetworkEquipment', endpoint: '/Assets/NetworkEquipment' },
    {           name: 'Printers',         endpoint: '/Assets/Printer' },
    {           name: 'Phones',           endpoint: '/Assets/Phone' },
    {           name: 'Peripherals',      endpoint: '/Assets/Peripheral' },
    {           name: 'Software',         endpoint: '/Assets/Software' },
    {           name: 'SoftwareLicense',  endpoint: '/Assets/SoftwareLicense' },
    {           name: 'Contracts',        endpoint: '/Management/Contract' },
    {           name: 'Documents',        endpoint: '/Management/Document' },
    {           name: 'Budgets',          endpoint: '/Management/Budget' },
    {           name: 'Suppliers',        endpoint: '/Management/Supplier' },
    {           name: 'Contacts',         endpoint: '/Management/Contact' },
    {           name: 'Projects',         endpoint: '/Project' },
    {           name: 'KnowledgeBase',    endpoint: '/Setup/KnowledgeBase' },
    {           name: 'Users',            endpoint: '/Administration/User' },
]